### ISSUE TITLE
Bug hunting sketch-notes : can not share to scrap

### ISSUE THREAD

**Issue by muhammadrival** [maks/Sketch-Notes#21]
#### Expected behavior

This application should support file storage from notes to memos

#### Actual behavior

In fact here does not support file storage from notes to memos

#### How to reproduce

* Download the Application in Playstore [here](https://play.google.com/store/apps/details?id=com.manichord.sketchnotes)
* Launch App
* then write something note
- then send to memo via shere button
- there is no file in the show
- whereas my memo supports image files
- n the video there I apply the proof
- Device used: Samsung Grand prime SM-G530

* Operating System: Android version 4.4.4

* Application version: 1.0.6
*  [Github](https://github.com/maks/Sketch-Notes/)

#### Recording Of The Bug
https://youtu.be/7nt0PLUZcq4

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@muhammadrival/bug-hunting-sketch-notes-can-not-share-to-scrap">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by maks** [comment]
Thank you for reporting this, especially for including the video. However this is an issue with the memo app and not sketchnotes.
